name: deploy
on:
  push:
    branches:
      - main
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/90532848382/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'pf-bdcom@prefab-mapper-373309.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'hello'
        runtime: 'go119'
          # projectのregionをusで作っちゃってたのでここで指定してもダメだった。
          #        region: 'asia-northeast1'


    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
